name: Node.JS Installation

on: push

jobs:
  node-configuration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - name: Verify Weather Node is Installed or Not
        run: node --version
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
